### ISSUE TITLE
Get exact number of points

### ISSUE THREAD

**Issue by melhashash** [BAILOOL/ANMS-Codes#15]
Thanks for the work.

I can get the exact number of returned points using `brownANMS`, but using other methods, I couldn't, even when I set the `tolerance` to `0`.

Is there a quick modification to get the exact number of points for the other methods?

**Comment by BAILOOL** [comment]
Hi @melhashash, thank you for your interest. The quickest modification to get the exact number of points is to request more points than you originally need with a reasonable tolerance (for an algorithm to converge) and then apply TopN filtering to select the exact number of points you need. Since you will be doing TopN on already homogeneously distributed points on the image, you will still maintain that property. Additional, TopN complexity is linear with respect to the filtered number of points (sorted in decreasing order of strength at this stage) and is not a bottleneck.

**Comment by melhashash** [comment]
Thanks for the detailed answer.
