### ISSUE TITLE
Can I use in ORB Matchs

### ISSUE THREAD

**Issue by Grungeby52** [BAILOOL/ANMS-Codes#31]
Hello,

I want to use my key points that I got here in the ORB. Do you think this is possible? 

Best Regards

Onur Güzeldemirci

**Comment by BAILOOL** [comment]
@Grungeby52 great question. I assume your ORB keypoints are based on OpenCV. 

ORB uses FAST keypoints under the hood and filters them with TopN point selection based on keypoint strength before extracting the ORB descriptor. Several ideas come to mind:

- In order to use ANMS algorithms in this repo without modifying too much code, you'd need to return many more points from the ORB detector and then apply ANMS on those. This is not practical if speed is important.

- Disabling TopN filtering would be another option but it would require modifying OpenCV core functionality. Not recommended.

- The most practical solution is to extract FAST keypoints manually, filter them using ANMS, and extract ORB descriptors for selected keypoints. This is exactly what we did for experiments in the [paper](https://www.researchgate.net/publication/323388062_Efficient_adaptive_non-maximal_suppression_algorithms_for_homogeneous_spatial_keypoint_distribution) (Section 4.5: Application to SLAM)

**Comment by Grungeby52** [comment]
Hello,

Thanks for quick feedback,
As far as I understand, you are telling me to homogenize the key point I got with FAST in the 3rd recommendation. Did I get it right?

Best  Regards,

Onur Güzeldemirci

**Comment by BAILOOL** [comment]
@Grungeby52, yeah, I'd recommend using the 3rd option: get FAST points, homogenize them with ANMS, and then extract ORB descriptor for the selected points.
