### ISSUE TITLE
Effectiveness for monocular SLAM

### ISSUE THREAD

**Issue by pawlusmall** [BAILOOL/ANMS-Codes#6]
Hi,

First of all, congratulations for your paper and thank you for your contribution to computer vision field.

After reading your paper and making some tests I can conclude that this new ANMS approach can be helpful for stereo systems where line matching can be used to get correspondences from a pair of images. However, when feature matchers are used, I get much better results with the bucketing approach, probably because feature matchers don't work well with low contrast features (although well distributed).

I'm my tests I've used ORB for keypoints and descriptors extraction, and tested correspondences with both a Brute Force matcher and a Flann matcher.

Could you share your thoughts about using ANMS approaches for monocular systems? Any recommendation to improve keypoint matching?

**Comment by rameau-fr** [comment]
Dear Pablo,

your observation is certainly valid. When detecting keypoints, there is a certain trade-off between their spatial distribution and their repeatability. If you only want to use a restricted number of points they might be difficult to match. 
We recommend to use a keypoint tracker such as KLT instead of a matching approach (like KNN or BF). we actually use this strategy in our own SLAM system and it provides very stable tracks and compelling results. 
For sparse stereo matching, you can detect keypoints on the left image and find correspondences by line scanning.

Best regards,

**Comment by pawlusmall** [comment]
Thank you for you answer,

Using a KLT tracker could be useful for fixed focus cameras, in fact, we use it as a complement in our monocular keyframe-based SLAM. However, any time we get an occlusion we have to perform relocalization using feature matching, and there is when we need strong keypoints.

Anyway, I think we a exploring very different SLAM approaches. In our case we use it for Augmented Reality in mobile phones where only one camera exists and we have to deal with very limited computing resources. I guess you're probably using it with stereo cameras for autonomous driving so what is good for your SLAM system could be bad for ours and vice versa.

Warm regards
