### ISSUE TITLE
Response vector

### ISSUE THREAD

**Issue by lgalardini** [BAILOOL/ANMS-Codes#8]
Hello everyone,

In **main.cpp** the following code 
`//Sorting keypoints by deacreasing order of strength
    vector<**int**> responseVector;
    for (unsigned int i =0 ; i<keyPoints.size(); i++) responseVector.push_back(keyPoints[i].response);
`

Since the response of a cv::Keypoint is a **float** value, I think that the responseVector should be float as well instead of int. In fact, if other detectors than FAST are used, the response vector is going to be populated of zeros because the range is different.

**Comment by BAILOOL** [comment]
@lgalardini you are right. it is a bug. `cv::KeyPoint::response` returns `float` . [Reference](https://docs.opencv.org/3.4/d2/d29/classcv_1_1KeyPoint.html#a1f163ac418c281042e28895b20514360).

I will fix it whenever I have time. Meanwhile, since you discovered this, you can create `Pull request` for this issue. Thank you for your contribution to the project!
